typography_spectrum: 0.5529281636700034
color:
  brandStrength: 0.25324711692519486
  lightness: 0.9767078887671232
  saturation: 0.9675813876092434
  rhythmicContrast: 0.6472740003373474
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.5491173618938774
author:
  name: Joel Cobos
  email: info@joelcobos.com
  url: www.tutorialesdehipnosis.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9d7516f9-dbf2-48cc-8303-ec3fe44ddb64.jpg
name: Tutoriales de Hipnosis
navigation:
  - name: Canal de Youtube
    url: 'https://www.youtube.com/joelcoboshipnosis'
    type: external
title: Tutoriales de Hipnosis
description: Aprende a hipnotizar gratis
